# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

TWILIO_TEST_SID: ACa171101be9c3be04ec9a72640a04b078
TWILIO_TEST_TOKEN: ac2f4cbe674b1d654073ec568c70d24c
TWILIO_TEST_PHONE: '+15005550006'

TWILIO_LIVE_SID: ACc98effb49ab3a5c11d3b5b20067cd664
TWILIO_LIVE_TOKEN: f9a5650ef82e80a7e9d143c36a533ef5
TWILIO_ACCOUNT_PHONE: '+17207062181'
